// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PondLite.Api.Data;

#nullable disable

namespace PondLite.Api.Migrations
{
    [DbContext(typeof(PondLiteDbContext))]
    [Migration("20260506015555_AddFrogFoundation")]
    partial class AddFrogFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PondLite.Api.Models.AuthToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("PondLite.Api.Models.Frog", b =>
                {
                    b.Property<Guid>("FrogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentMood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RelationshipMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("FrogId");

                    b.HasIndex("RelationshipMemberId")
                        .IsUnique();

                    b.ToTable("Frogs");
                });

            modelBuilder.Entity("PondLite.Api.Models.Relationship", b =>
                {
                    b.Property<Guid>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RelationshipId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("PondLite.Api.Models.RelationshipMember", b =>
                {
                    b.Property<Guid>("RelationshipMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("RelationshipMemberId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("RelationshipId", "UserAccountId")
                        .IsUnique();

                    b.ToTable("RelationshipMembers");
                });

            modelBuilder.Entity("PondLite.Api.Models.UserAccount", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountId");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("PondLite.Api.Models.AuthToken", b =>
                {
                    b.HasOne("PondLite.Api.Models.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PondLite.Api.Models.Frog", b =>
                {
                    b.HasOne("PondLite.Api.Models.RelationshipMember", "RelationshipMember")
                        .WithOne("Frog")
                        .HasForeignKey("PondLite.Api.Models.Frog", "RelationshipMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelationshipMember");
                });

            modelBuilder.Entity("PondLite.Api.Models.RelationshipMember", b =>
                {
                    b.HasOne("PondLite.Api.Models.Relationship", "Relationship")
                        .WithMany("Members")
                        .HasForeignKey("RelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PondLite.Api.Models.UserAccount", "UserAccount")
                        .WithMany("RelationshipMembers")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relationship");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PondLite.Api.Models.Relationship", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("PondLite.Api.Models.RelationshipMember", b =>
                {
                    b.Navigation("Frog");
                });

            modelBuilder.Entity("PondLite.Api.Models.UserAccount", b =>
                {
                    b.Navigation("RelationshipMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
